config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'
  resources :posts do
    resources :comments, only: :create
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :message, presence: true
	validates :picture, presence: true
	
	belongs_to :user
	has_many :comments

	mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def render_not_found(status=:not_found)
    render :text => "#{status.to_s.titleize} :(", :status => status
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:create]
  
  def create
    @post = Post.find_by_id(params[:post_id])
    return render_not_found if @post.blank?
    
    @post.comments.create(comment_params.merge(:user_id => current_user))
    redirect_to root_path
  end
  
  private

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.create(post_params)
		if @post.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@post = Post.find_by_id(params[:id])
		if @post.blank?
			render text: "Not Found :(", status: :not_found
		end
	end

	def edit
		@post = Post.find_by_id(params[:id])
		return render_not_found if @post.blank?
	  return render_not_found(:forbidden) if @post.user != current_user
	end

	def update
	  @post = Post.find_by_id(params[:id])
	  return render_not_found if @post.blank?
	  return render_not_found(:forbidden) if @post.user != current_user

	  @post.update_attributes(post_params)
	  
	  if @post.valid?
	    redirect_to root_path
	  else
	    return render :edit, :status => :unprocessable_entity
	  end
	end

	def destroy
		@post = Post.find_by_id(params[:id])
		return render_not_found if @post.blank?
		return render_not_found(:forbidden) if @post.user != current_user
		@post.destroy
		redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:message, :picture)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grammable</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  

</head>
<body>
	  <div class="top-nav">
    <div class="col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <div class="brand pull-left">
        Grammable
      </div>
      <div class="add pull-right">
        <% if current_user %>
          Welcome, <%= current_user.email %>.
          <%= link_to "New Post", new_post_path %>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </div>
    <br class="clear-fix" />
  </div>

	<% if notice.present? %> 
		<p class="notice"><%= notice %></p> 
	<% end %> 
	<% if alert.present? %> 
		<p class="alert"><%= alert %></p> 
	<% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 card form">
  <h2>Edit Post</h2>

  <%= simple_form_for @post do |f| %>
    <%= f.input :message %>
    <%= f.input :picture %>
    <%= f.submit 'Update', class: 'my-btn' %>
  <% end %>
  
</div>

app/views/posts/index.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
  <% @posts.each do |post| %>
	  <div class="card">
	    <div class="handle"><%= post.user.email %></div>
	    <%= image_tag post.picture, :class => 'img-responsive' %>
	    <p>
	      <%= post.message %>
	    </p>

	    <div class="post-actions pull-right">
	      <% if current_user && current_user == post.user %>
	        <%= link_to 'Edit', edit_post_path(post) %>
	        <%= link_to 'Destroy', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
	      <% end %>
	    </div>
	    <br class="clear-fix" />
	    <div class="comments">
	      <h3>Comments</h3>
	      <% post.comments.each do |comment| %>
	        <div class="comment">
	          <span class="comment_handle">
	            <%= comment.user.email %>
	          </span>
	          
	          <%= comment.message %>
	        </div>
	      <% end %>
	      <h4>Add a comment</h4>
	      <%= simple_form_for Comment.new, :url => post_comments_path(post) do |f| %>
	        <%= f.input :message %>
	        <%= f.submit 'Add Comment', class: 'my-btn' %>
	      <% end %>
	    </div>

	  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 card form">
  
  <h1>New Post</h1>
  
  <%= simple_form_for @post do |f| %>
    <%= f.input :message %>
    <%= f.input :picture %>
    <%= f.submit "Post!", :class => 'my-btn' %>  <% end %>
  
</div>